/* ========== SIGNAL REPORTS ========== */
(function(){
'use strict';

let reportCounter=0;

function create(opts){
  reportCounter++;
  const id='report-'+reportCounter;
  const title=opts.title||'Investigation Report';
  const sections=opts.sections||[];

  // Build report body
  const body=document.createElement('div');
  body.className='signal-report';
  body.style.cssText='padding:16px;color:#e0e0e0;font-family:"Space Mono",monospace;font-size:12px;line-height:1.6;overflow:auto;height:100%';

  // Header
  const header=document.createElement('div');
  header.style.cssText='border-bottom:1px solid rgba(0,255,136,0.2);padding-bottom:12px;margin-bottom:16px';
  header.innerHTML=`<h2 style="font-family:Orbitron,monospace;font-size:14px;color:#00ff88;letter-spacing:2px;margin:0 0 4px">${escHtml(title)}</h2>`+
    `<div style="font-size:9px;color:#666;letter-spacing:1px">GENERATED BY SIGNAL &mdash; ${new Date().toLocaleString()}</div>`;
  body.appendChild(header);

  // Sections
  sections.forEach(function(sec){
    const div=document.createElement('div');
    div.style.cssText='margin-bottom:20px';
    div.innerHTML=`<h3 style="font-family:Orbitron,monospace;font-size:11px;color:#00ccff;letter-spacing:1.5px;margin:0 0 8px;border-left:3px solid #00ccff;padding-left:8px">${escHtml(sec.heading)}</h3>`+
      `<div style="color:#ccc;font-size:11px;line-height:1.7">${escHtml(sec.text).replace(/\n/g,'<br>')}</div>`;

    // Optional chart
    if(sec.chart&&sec.chart.data&&window.SignalCharts){
      const chartDiv=document.createElement('div');
      chartDiv.style.cssText='margin:12px 0;padding:8px;background:rgba(0,0,0,0.3);border:1px solid rgba(255,255,255,0.05);border-radius:4px';
      div.appendChild(chartDiv);
      try{
        SignalCharts.render(chartDiv,sec.chart);
      }catch(e){
        chartDiv.innerHTML='<div style="color:#666;font-size:10px">[Chart could not be rendered]</div>';
      }
    }
    body.appendChild(div);
  });

  // Download button
  const dlBtn=document.createElement('button');
  dlBtn.style.cssText='display:block;margin:20px auto;padding:8px 20px;background:rgba(0,255,136,0.1);border:1px solid #00ff88;color:#00ff88;font-family:Orbitron,monospace;font-size:10px;letter-spacing:1.5px;cursor:pointer;border-radius:3px';
  dlBtn.textContent='DOWNLOAD HTML';
  dlBtn.addEventListener('click',function(){downloadReport(title,body)});
  body.appendChild(dlBtn);

  // Create window
  var win=WindowManager.create({
    id:id,
    title:'<span class="icon">&#9993;</span> '+title.toUpperCase(),
    content:body,
    defaultPos:{right:40,top:60},
    defaultSize:{width:600,height:500},
    minSize:{width:400,height:300}
  });
  win.show();
  return{windowId:id};
}

function downloadReport(title,bodyEl){
  // Clone SVGs as static snapshots
  const clone=bodyEl.cloneNode(true);
  // Remove download button from the exported version
  var btns=clone.querySelectorAll('button');
  btns.forEach(function(b){b.remove()});

  var html='<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">'
    +'<meta name="viewport" content="width=device-width,initial-scale=1">'
    +'<title>'+escHtml(title)+' — Strange Signals Report</title>'
    +'<style>'
    +'body{background:#05060f;color:#e0e0e0;font-family:"Courier New",monospace;font-size:12px;line-height:1.6;max-width:800px;margin:0 auto;padding:24px}'
    +'h2{font-size:16px;color:#00ff88;letter-spacing:2px;margin:0 0 4px}'
    +'h3{font-size:12px;color:#00ccff;letter-spacing:1.5px;margin:16px 0 8px;border-left:3px solid #00ccff;padding-left:8px}'
    +'svg text{font-family:"Courier New",monospace}'
    +'</style></head><body>'
    +clone.innerHTML
    +'</body></html>';

  var blob=new Blob([html],{type:'text/html'});
  var url=URL.createObjectURL(blob);
  var a=document.createElement('a');
  a.href=url;
  a.download=title.replace(/[^a-zA-Z0-9 ]/g,'').replace(/ +/g,'-').toLowerCase()+'.html';
  a.click();
  URL.revokeObjectURL(url);
}

function escHtml(s){
  if(!s)return'';
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function download(opts){
  var title=opts.title||'Investigation Report';
  var sections=opts.sections||[];
  var html='<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">'
    +'<meta name="viewport" content="width=device-width,initial-scale=1">'
    +'<title>'+escHtml(title)+' — Strange Signals Report</title>'
    +'<style>'
    +'body{background:#05060f;color:#e0e0e0;font-family:"Courier New",monospace;font-size:12px;line-height:1.6;max-width:800px;margin:0 auto;padding:24px}'
    +'h2{font-size:16px;color:#00ff88;letter-spacing:2px;margin:0 0 4px}'
    +'h3{font-size:12px;color:#00ccff;letter-spacing:1.5px;margin:16px 0 8px;border-left:3px solid #00ccff;padding-left:8px}'
    +'.section{margin-bottom:20px}'
    +'.meta{font-size:9px;color:#666;letter-spacing:1px}'
    +'</style></head><body>'
    +'<h2>'+escHtml(title)+'</h2>'
    +'<div class="meta">GENERATED BY SIGNAL &mdash; '+new Date().toLocaleString()+'</div>'
    +'<hr style="border:none;border-top:1px solid rgba(0,255,136,0.2);margin:12px 0 16px">';
  sections.forEach(function(sec){
    html+='<div class="section"><h3>'+escHtml(sec.heading)+'</h3>'
      +'<div>'+escHtml(sec.text).replace(/\n/g,'<br>')+'</div></div>';
  });
  html+='</body></html>';
  var blob=new Blob([html],{type:'text/html'});
  var url=URL.createObjectURL(blob);
  var a=document.createElement('a');
  a.href=url;
  a.download=title.replace(/[^a-zA-Z0-9 ]/g,'').replace(/ +/g,'-').toLowerCase()+'.html';
  a.click();
  URL.revokeObjectURL(url);
}

window.SignalReports={create,download};

})();
